name: kishan_se
description: Kishan se application


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


#------PACKAGES------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  intl: ^0.17.0
  logger: ^2.0.2+1
  flutter_native_splash: ^1.2.0

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  #state Management
  get: ^4.6.5
  get_storage: ^2.1.1

  #Product Specific



  #--------------/Packages End----------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #-----------LOCAL ASSETS---------------#
  assets:
    - assets/icons/brands/
    - assets/images/
    - assets/logos/
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
